#!/bin/bash



servers=("ada3.computing.clemson.edu" "ada4.computing.clemson.edu" "ada5.computing.clemson.edu" "ada6.computing.clemson.edu" "ada7.computing.clemson.edu" "ada8.computing.clemson.edu" "ada9.computing.clemson.edu" "ada10.computing.clemson.edu" "ada11.computing.clemson.edu" )
numsrvrs=${#servers[@]}
commd="cd Documents/cpsc8190/starter; bin/$1"
st=$2
en=$3
itr=0
range=$((en - st))
inc=$((range/numsrvrs + 1))

base_cmd=$1

ctr_c()
{
   for server in "${servers[@]}"; do
	cmd="killall $base_cmd"
	#echo $server $cmd 
	ssh -tt "$server" "$cmd" &
   done
   wait
   exit
}

trap ctr_c SIGINT

for server in "${servers[@]}"; do
	s=$((st + itr*inc))
	e=$((st + itr*inc + inc - 1))
	e=$(( e > en ? en : e))
	# echo "s $s e $e"
	cmd="$commd -s $s -e $e $4 >| bin/null"
	# echo $cmd
	itr=$((itr + 1))
	ssh -tt "$server" "$cmd" &

done

wait

echo "Renders Complete"
