#!/bin/bash



servers=("ada3.computing.clemson.edu" "ada4.computing.clemson.edu" "ada5.computing.clemson.edu" "ada6.computing.clemson.edu" "ada7.computing.clemson.edu" "ada8.computing.clemson.edu" "ada9.computing.clemson.edu" "ada10.computing.clemson.edu" "ada11.computing.clemson.edu" )
numsrvrs=${#servers[@]}
commd="cd Documents/cpsc8190/starter; bin/$1"
st=$2
en=$3
itr=0
range=$((en - st))
inc=$((range/numsrvrs + 1))

base_cmd=$1

ctr_c()
{
   for server in "${servers[@]}"; do
	cmd="killall $base_cmd"
	#echo $server $cmd 
	ssh -tt "$server" "$cmd" &
   done
   wait
   exit
}

trap ctr_c SIGINT

for frame in $(seq "$st" "$en"); do
	cmd="$commd -f $frame >| bin/null"
	# echo $cmd
	echo ssh -tt "$server" "$cmd" &

done

wait

echo "Renders Complete"
